name: Fourth Workflow

on: [push]

jobs:
  ascii_job_ShellScript:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Execute Shell Script
        run: |
          chmod +x ascii-script.sh
          ./ascii-script.sh
